### ISSUE TITLE
Docker Compose v1 compatibility issues

### ISSUE THREAD

**Issue by jvann94** [ubergeek77/Lemmy-Easy-Deploy#8] opened 2023-06-21 01:16 UTC
```
Checking proxy... unknown shorthand flag: 'p' in -p
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
``` 

when running deploy.sh on ubuntu server 22 vm

**Comment by ubergeek77** [comment] 2023-06-21 01:20
Oh whoops. I forgot to use the autodetected compose command in the service checker. Sorry about that! Fix coming ASAP.

**Comment by ubergeek77** [comment] 2023-06-21 01:23
Please run `git pull ` to update to Lemmy Easy Deploy 1.0.7 and let me know if that resolves the issue!

**Comment by jvann94** [comment] 2023-06-21 01:36
it no longer errors about the -p flag but I do not know id this issue is related

```
reating lemmy-easy-deploy_proxy_1    ...

ERROR: for lemmy-easy-deploy_proxy_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for proxy  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

Checking deployment status...
Checking proxy... ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml

"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
``` 

New to docker, does this mean I need to move deploy.sh to live and run it there?

**Comment by ubergeek77** [comment] 2023-06-21 01:42
No, that's not what it means. This is a new error I've never seen before. It looks like your Docker service is "stuck."

Can you try these steps for me?

```
cd ./live

docker-compose -p "lemmy-easy-deploy" down

# If the above command errors, try this instead, also from the ./live folder
docker-compose down
```

Then, from the `Lemmy-Easy-Deploy` folder, try running `./deploy.sh -f`

If you are still having issues, I would recommend either restarting your Docker service (`sudo systemctl restart docker`), or outright rebooting your server. Then you can try my above troubleshooting steps once more.

Let me know how all that goes!

**Comment by jvann94** [comment] 2023-06-21 02:19
its still having a hard time with the proxy and finding the docker file.

```
Creating lemmy-easy-deploy_proxy_1    ... done

Checking deployment status...
Checking proxy... ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml

"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
```

**Comment by ubergeek77** [comment] 2023-06-21 02:29
Can you please `git pull ` again, run `deploy.sh -d`, then paste the output for me here? I need some diagnostic info to understand what's going wrong here.

**Comment by ubergeek77** [comment] 2023-06-21 02:49
I've pushed another fix that I believe will resolve this for good. I suspect you might be using Docker Compose v1, which apparently doesn't like only having the stack name passed in with `-p`. I now `cd` into `./live` before performing service checks.

Please `git pull` one last time, try again, and if you are still having issues, please include the output of `./deploy.sh -d` in your next message!

**Comment by ubergeek77** [comment] 2023-06-21 03:41
I have reproduced your issue on Ubuntu 22.04, and I can confirm that the issue is now fixed. Please update Lemmy-Easy-Deploy and try your deployment again.

Please note: this happened because you are using an old and unsupported version of Docker Compose. Lemmy Easy Deploy should still work with the fixes I have applied, but I still recommend you follow the advice given in the Readme, and [install the official version of Docker rather than the unsupported version supplied by Ubuntu](https://docs.docker.com/engine/install/ubuntu/).

Let me know if you have any additional issues!

**Closed by ubergeek77** 2023-06-21 03:41 UTC
