### ISSUE TITLE
Install fails - Password authentication failed for user "lemmy" connecting to postgres://lemmy[etc]

### ISSUE THREAD

**Issue by Taubin** [ubergeek77/Lemmy-Easy-Deploy#14] opened 2023-06-23 21:21 UTC
**Describe the bug**
> What happened? Post any relevant log snippets.

Installation fails with "password authentcation failed for user 'lemmy'" for the sql database

pvkKEoZ4@postgres:5432/lemmy: FATAL:  password authentication failed for user "lemmy"
lemmy-easy-deploy-lemmy-1     | ', crates/db_schema/src/utils.rs:161:56
lemmy-easy-deploy-lemmy-1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Diagnostic Information**
> Run `./deploy.sh -d` and paste the output below:
```
==== Docker Information ====
Detected runtime: docker (Docker version 24.0.2, build cb74dfc)
Detected compose: docker compose (Docker Compose version v2.18.1)
   Runtime state: OK

==== System Information ====
MEMORY:                total        used        free      shared  buff/cache   available
Mem:           1.2Gi       348Mi       134Mi       5.0Mi       725Mi       674Mi
Swap:          1.0Gi       196Mi       827Mi

KERNEL: 5.15.0-75-generic (x86_64)
SHELL: /bin/bash
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

==== Lemmy Easy Deploy Information ====
Version: 1.1.2
Integrity:
    836ee08012d40fe0084f54d01dc48c237019e7c2d011d927efb279522ef00e5d  ./deploy.sh
    1e9b0c0988998dcc33cb0fbfdb0e1679229424e724f898b797380adc7d102446  ./templates/Caddy-Dockerfile.template
    c1202e70662dd2228da36a35a0f38ec8fc81bec8964d7315d02e8671a58dd7d7  ./templates/Caddyfile.template
    7754ef7e8aa7e925becfcbbda0f873387533397a0756405741f4f4b9eb7f7253  ./templates/cloudflare.snip
    1df196524e8d55a4be93b5bf401669d61b372c4f6f7670da83ab1947631fd0ed  ./templates/compose-email.snip
    839ce56196227e2bac2291ee045ef95bc6af9c9706396352f39cb0812754c5c1  ./templates/compose-email-volumes.snip
    06cfd023e5c61bd4cbda9809ba35e4e99eaf090e3d674612bc3c04fe58eee397  ./templates/docker-compose.yml.template
    308b8a122ee03cb9f5279fc2ad79663b0bffb2ed2a4042b96f678715cc997914  ./templates/lemmy-email.snip
    8f25408461972b9b66ee3c4d3f6430e2e1eaa950394d2d8b7e3d1287fe0d8f07  ./templates/lemmy.hjson.template

==== Settings ====
BUILD_FROM_SOURCE=false
CADDY_HTTP_PORT=80
CADDY_HTTPS_PORT=443
USE_EMAIL=false
CADDY_DISABLE_TLS=false
POSTGRES_POOL_SIZE=5
TLS_ENABLED=true

==== Generated Files ====
total 32K
drwxrwxr-x 2 1000 1000 4.0K Jun 23 21:08 caddy
-rw-rw-r-- 1 1000 1000   89 Jun 23 21:08 caddy.env
-rw-rw-r-- 1 1000 1000 2.0K Jun 23 21:08 docker-compose.yml
-rw-rw-r-- 1 1000 1000   50 Jun 23 21:08 lemmy.env
-rw-rw-r-- 1 1000 1000  469 Jun 23 21:08 lemmy.hjson
-rw-rw-r-- 1 1000 1000   49 Jun 23 21:08 pictrs.env
-rw-rw-r-- 1 1000 1000   39 Jun 23 21:08 postfix.env
-rw-rw-r-- 1 1000 1000   51 Jun 23 21:08 postgres.env
```

lemmy.hjson:

```
{
  setup: {
    admin_username: "Dusty"
    admin_password: "[redacted]"
    site_name: "Lemmy"
  }

  hostname: "lemmy.[redacted].com"
  bind: "0.0.0.0"
  port: 8536
  tls_enabled: true

  pictrs: {
    url: "http://pictrs:8080/"
    api_key: "Hb4 [rest redacted will post fully if needed]"
  }

  database: {
    user: "lemmy"
    password: "nvNHu [rest redacted will post fully if needed]"
    host: "postgres"
    port: 5432
    database: "lemmy"
    pool_size: 5
  }

}
```

**Comment by ubergeek77** [comment] 2023-06-23 21:30
Is this a brand new deployment? Or an update to an existing one?

I am getting all kinds of problems on 0.18 on my own server, and now that 0.18 is out, the official Lemmy issue tracker is getting dogpiled with issues. They really shouldn't have rushed this release.

If this was a brand new deployment, can you try `./deploy.sh -u 0.17.4 -f` and seeing if that works?

If you have the same issue on 0.17.4, I can try diagnosing further.

**Comment by ubergeek77** [comment] 2023-06-23 21:32
Also, I can see from your redacted strings that `nvNHu` and `pvkKEoZ4` do not match.

Is the password in `postgres.env` different from the one in `lemmy.hjson`? That shouldn't happen (I'm actually not sure how it could happen), but it could be the cause.

**Comment by Taubin** [comment] 2023-06-23 21:37
Thanks I'll try rolling back to the 0.17 

I had a previous installation on there that I had installed through docker-compose (what a pain that was). I've since wiped it and was attempting to install through the script for .18.

The passwords do match for postgres.env and lemmy.hjson

There's nothing important on this particular server, so I'll wipe the server and try again. Thank you for the help, I'll update if it doesn't work after the wipe.

**Comment by ubergeek77** [comment] 2023-06-23 21:41
Ah, I think I know what happened then. And I may need to find a clever way to warn users about it.

The variable may be called `POSTGRES_PASSWORD`, but the `postgres` container only uses it to ***initialize*** the database. And since deleting the `./live` folder doesn't delete the volumes made by Docker Compose, you likely had an old postgres volume that had the old password set in it. If you are REALLY SUPER SURE you want to delete your old data, you can clear your old volume like this:

```
docker volume rm lemmy-easy-deploy_postgres_data
```

You can also list other volumes used by this project and optionally delete them just like above:


```
docker volume ls
```

I am like 99% sure that's what happened, so I will close this, but please feel free to come back and ping me if I need to look into the issue further!

**Closed by ubergeek77** 2023-06-23 21:41 UTC
